version: '3.7'
services:
  pg-server:
    image: postgres:15.1
    container_name: db-lms
    restart: always
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: vclude
      POSTGRES_PASSWORD: 123qweasd
    ports:
      - "5432:5432"
    volumes:
      - ./pg:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U vclude -d lms
      interval: 10s
      timeout: 3s
      retries: 5
  redis:
    container_name: redis-lms
    image: redis:latest
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
  lms-api:
    build: .
      ports:
        - "5000:8079"