CREATE SEQUENCE  IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE client (
  id BIGINT NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE company (
  id BIGINT NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_company PRIMARY KEY (id)
);

CREATE TABLE grade (
  id BIGINT NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_grade PRIMARY KEY (id)
);

CREATE TABLE karyawan (
  id BIGINT NOT NULL,
   company_id BIGINT,
   nik VARCHAR(255),
   name VARCHAR(255),
   contact_email VARCHAR(255),
   position_id BIGINT,
   tl_id BIGINT,
   status_id BIGINT,
   first_join_date TIMESTAMP WITHOUT TIME ZONE,
   start_contract TIMESTAMP WITHOUT TIME ZONE,
   end_contract TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_karyawan PRIMARY KEY (id)
);

CREATE TABLE karyawan_client (
  id BIGINT NOT NULL,
   status_id BIGINT,
   sales_id BIGINT,
   placement_id BIGINT,
   client_id BIGINT,
   project_name VARCHAR(255),
   pic_timesheet_d2d VARCHAR(255),
   pic_contact_hp VARCHAR(255),
   pic_email VARCHAR(255),
   cutoff_timesheet VARCHAR(255),
   timesheet_note VARCHAR(255),
   start_contract TIMESTAMP WITHOUT TIME ZONE,
   end_contract TIMESTAMP WITHOUT TIME ZONE,
   idle_alert BIGINT NOT NULL,
   perpanjangan BOOLEAN NOT NULL,
   status_project_id BIGINT,
   durasi_perpanjangan BIGINT NOT NULL,
   karyawan_id BIGINT,
   CONSTRAINT pk_karyawan_client PRIMARY KEY (id)
);

CREATE TABLE position (
  id BIGINT NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_position PRIMARY KEY (id)
);

CREATE TABLE status (
  id BIGINT NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_status PRIMARY KEY (id)
);

CREATE TABLE user_role (
  user_id BIGINT NOT NULL,
   roles VARCHAR(255)
);

CREATE TABLE user_to_employee (
  employee_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE karyawan_client ADD CONSTRAINT FK_KARYAWAN_CLIENT_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

ALTER TABLE karyawan_client ADD CONSTRAINT FK_KARYAWAN_CLIENT_ON_KARYAWAN FOREIGN KEY (karyawan_id) REFERENCES karyawan (id);

ALTER TABLE karyawan_client ADD CONSTRAINT FK_KARYAWAN_CLIENT_ON_PLACEMENT FOREIGN KEY (placement_id) REFERENCES client (id);

ALTER TABLE karyawan_client ADD CONSTRAINT FK_KARYAWAN_CLIENT_ON_SALES FOREIGN KEY (sales_id) REFERENCES karyawan (id);

ALTER TABLE karyawan_client ADD CONSTRAINT FK_KARYAWAN_CLIENT_ON_STATUS FOREIGN KEY (status_id) REFERENCES status (id);

ALTER TABLE karyawan_client ADD CONSTRAINT FK_KARYAWAN_CLIENT_ON_STATUS_PROJECT FOREIGN KEY (status_project_id) REFERENCES client (id);

ALTER TABLE karyawan ADD CONSTRAINT FK_KARYAWAN_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE karyawan ADD CONSTRAINT FK_KARYAWAN_ON_POSITION FOREIGN KEY (position_id) REFERENCES position (id);

ALTER TABLE karyawan ADD CONSTRAINT FK_KARYAWAN_ON_STATUS FOREIGN KEY (status_id) REFERENCES status (id);

ALTER TABLE karyawan ADD CONSTRAINT FK_KARYAWAN_ON_TL FOREIGN KEY (tl_id) REFERENCES users (id);

ALTER TABLE user_role ADD CONSTRAINT fk_user_role_on_users FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_to_employee ADD CONSTRAINT fk_usetoemp_on_employees FOREIGN KEY (employee_id) REFERENCES karyawan (id);

ALTER TABLE user_to_employee ADD CONSTRAINT fk_usetoemp_on_users FOREIGN KEY (user_id) REFERENCES users (id);